### ISSUE TITLE
Breaking changes in Ghost 0.10.0

### ISSUE THREAD

**Issue by kirrg001** [spanishdict/ghost-s3-compat#10]
Hey!

We will soon release Ghost `0.10.0` - in about 2 days.
It contains breaking changes for the storage adapter, see https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module.

**Comment by acburdine** [comment]
I've got a fix for this 😄

**Comment by krokofant** [comment]
This projects seems to implement all the features, like delete, for s3.
https://github.com/colinmeinke/ghost-storage-adapter-s3

**Comment by JuanCaicedo** [comment]
@krokofant that project looks good, but as far as I can tell they don't provide the ability to migrate from local storage to S3 storage, which is our goal with this project. I say that because `serve` is a NOOP
