### ISSUE TITLE
Add support for custom endpoint

### ISSUE THREAD

**Issue by OmgImAlexis** [spanishdict/ghost-s3-compat#12]
If you added support to override the endpoint then [minio](https://github.com/minio/minio) and other s3 compatible servers can be used with this.

**Comment by JuanCaicedo** [comment]
Sorry to take a while to get to this. I've never had a use case for minio, so I don't plan on working on this. Would you be interested in making a PR for this? It should be pretty straight forward I can help you get started.

**Comment by markstos** [comment]
For this looking for this, an alternate module provides it: https://github.com/colinmeinke/ghost-storage-adapter-s3
