### ISSUE TITLE
Remove redundancy install

### ISSUE THREAD

**Issue by krokofant** [spanishdict/ghost-s3-compat#13]
``` bash
$ npm install ghost-s3-compat
$ mkdir content/storage
$ cp -r node_modules/ghost-s3-compat content/storage/ghost-s3-compat
```

This seems like it's harder then necessary to maintain.

I'm using this solution, are there any downsides to this compared to the one above?

``` bash
$ npm install ghost-s3-compat
$ mkdir content/storage
$ mkdir content/storage/ghost-s3
$ echo module.exports = require('ghost-s3-compat') > content/storage/ghost-s3/index.js

```

**Comment by JuanCaicedo** [comment]
Yes, we were suggesting that way before, but changed it by request from the Ghost team requested it https://github.com/spanishdict/ghost-s3-compat/issues/5
