### ISSUE TITLE
Add Support for config.production.json

### ISSUE THREAD

**Issue by gaphu** [spanishdict/ghost-s3-compat#18]
In latest production version of ghost config.production.json file is available instead of config.js.
Please add some support for that.

**Comment by JuanCaicedo** [comment]
Hey @gaphu, SpanishDict isn't using Ghost any more, so I don't foresee that being something we'll work on. If you're interested in implementing that, go for it 😀

**Comment by susiloblogger** [comment]
Hi!
Is it possible to use this package on ghost version 5.33.x

**Comment by nanek** [comment]
No. This package is no longer maintained.
